

export const HSK1_ALL_LESSONS = [
  // =================== BÀI 1 ===================
  {
    lessonNumber: 1,
    title: 'Bài 1: Chào hỏi',
    hanziTitle: '你好 (Nǐ hǎo)',
    description: 'Từ vựng cơ bản để chào hỏi và xưng hô lịch sự',
    words: [
      {
        id: 'hsk1-1-01',
        hanzi: '你',
        pinyin: 'nǐ',
        vietnamese: 'bạn / anh / em / mày (ngôi thứ hai số ít)',
        hanViet: 'Nhĩ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 1: 你好',
        source: 'hsk1',
        exampleSentence: '你好！',
        examplePinyin: 'Nǐ hǎo!',
        exampleVietnamese: 'Chào bạn!',
        radicals: '亻 (nhân đứng) + 尔 (nhĩ)',
        mnemonic: 'Người (亻) đối diện với mình (尔) chính là Bạn (你).'
      },
      {
        id: 'hsk1-1-02',
        hanzi: '好',
        pinyin: 'hǎo',
        vietnamese: 'tốt / khỏe / đẹp / được',
        hanViet: 'Hảo',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 1: 你好',
        source: 'hsk1',
        exampleSentence: '你好吗？很好！',
        examplePinyin: 'Nǐ hǎo ma? Hěn hǎo!',
        exampleVietnamese: 'Bạn khỏe không? Rất khỏe!',
        radicals: '女 (nữ) + 子 (tử)',
        mnemonic: 'Gia đình có cả con gái (女) và con trai (子) là điều tốt đẹp (好).'
      },
      {
        id: 'hsk1-1-03',
        hanzi: '您',
        pinyin: 'nín',
        vietnamese: 'ngài / ông / bà / thầy (kính ngữ của 你)',
        hanViet: 'Nẫm / Nhĩ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 1: 你好',
        source: 'hsk1',
        exampleSentence: '老师，您好！',
        examplePinyin: 'Lǎoshī, nín hǎo!',
        exampleVietnamese: 'Thầy ơi, con chào thầy ạ!',
        radicals: '你 (bạn) + 心 (trái tim)',
        mnemonic: 'Đặt người bạn (你) ở trong trái tim (心) biểu thị sự tôn kính (您).'
      },
      {
        id: 'hsk1-1-04',
        hanzi: '你们',
        pinyin: 'nǐmen',
        vietnamese: 'các bạn / các anh / các chị (ngôi thứ hai số nhiều)',
        hanViet: 'Nhĩ môn',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 1: 你好',
        source: 'hsk1',
        exampleSentence: '你们好！',
        examplePinyin: 'Nǐmen hǎo!',
        exampleVietnamese: 'Chào các bạn!',
        radicals: '你 + 们 (hậu tố số nhiều)',
        mnemonic: 'Ghép từ 你 (bạn) và 们 (chúng/các).'
      },
      {
        id: 'hsk1-1-05',
        hanzi: '对不起',
        pinyin: 'duìbuqǐ',
        vietnamese: 'xin lỗi',
        hanViet: 'Đối bất khởi',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 1: 你好',
        source: 'hsk1',
        exampleSentence: '对不起，我来晚了。',
        examplePinyin: 'Duìbuqǐ, wǒ lái wǎn le.',
        exampleVietnamese: 'Xin lỗi, tôi đến muộn.',
        radicals: '对 + 不 + 起',
        mnemonic: 'Cảm thấy có lỗi, không ngẩng (起) mặt đối (对) diện được.'
      },
      {
        id: 'hsk1-1-06',
        hanzi: '没关系',
        pinyin: 'méi guānxi',
        vietnamese: 'không sao / không có gì',
        hanViet: 'Một quan hệ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 1: 你好',
        source: 'hsk1',
        exampleSentence: '没关系，请进！',
        examplePinyin: 'Méi guānxi, qǐng jìn!',
        exampleVietnamese: 'Không sao đâu, mời vào!',
        radicals: '没 (không có) + 关系 (quan hệ)',
        mnemonic: 'Không có vấn đề gì nghiêm trọng.'
      }
    ]
  },

  // =================== BÀI 2 ===================
  {
    lessonNumber: 2,
    title: 'Bài 2: Cảm ơn & Tạm biệt',
    hanziTitle: '谢谢你 (Xièxie nǐ)',
    description: 'Từ vựng cảm ơn, đáp lễ và từ biệt',
    words: [
      {
        id: 'hsk1-2-01',
        hanzi: '谢谢',
        pinyin: 'xièxie',
        vietnamese: 'cảm ơn',
        hanViet: 'Tạ tạ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 2: 谢谢你',
        source: 'hsk1',
        exampleSentence: '谢谢你的帮助！',
        examplePinyin: 'Xièxie nǐ de bāngzhù!',
        exampleVietnamese: 'Cảm ơn sự giúp đỡ của bạn!',
        radicals: '讠 (ngôn) + 身 (thân) + 寸 (thốn)',
        mnemonic: 'Dùng lời nói (讠) từ tận bản thân (身) với sự chừng mực (寸) để cảm ơn (谢).'
      },
      {
        id: 'hsk1-2-02',
        hanzi: '不',
        pinyin: 'bù',
        vietnamese: 'không / chẳng (phó từ phủ định)',
        hanViet: 'Bất',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 2: 谢谢你',
        source: 'hsk1',
        exampleSentence: '我不去。',
        examplePinyin: 'Wǒ bú qù.',
        exampleVietnamese: 'Tôi không đi.',
        radicals: '一 (nhất) + 𠃑 + 丨',
        mnemonic: 'Hình ảnh chim bay vút lên trời không chịu đậu xuống.'
      },
      {
        id: 'hsk1-2-03',
        hanzi: '不客气',
        pinyin: 'bú kèqi',
        vietnamese: 'đừng khách sáo / không có chi',
        hanViet: 'Bất khách khí',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 2: 谢谢你',
        source: 'hsk1',
        exampleSentence: 'A: 谢谢！ B: 不客气！',
        examplePinyin: 'A: Xièxie! B: Bú kèqi!',
        exampleVietnamese: 'A: Cảm ơn! B: Đừng khách sáo!',
        radicals: '不 + 客 (khách) + 气 (khí)',
        mnemonic: 'Không (不) cần phải giữ kẽ như khách (客).'
      },
      {
        id: 'hsk1-2-04',
        hanzi: '再见',
        pinyin: 'zàijiàn',
        vietnamese: 'tạm biệt / hẹn gặp lại',
        hanViet: 'Tái kiến',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 2: 谢谢你',
        source: 'hsk1',
        exampleSentence: '明天见，再见！',
        examplePinyin: 'Míngtiān jiàn, zàijiàn!',
        exampleVietnamese: 'Mai gặp lại, tạm biệt nhé!',
        radicals: '再 (lại lần nữa) + 见 (thấy/gặp)',
        mnemonic: 'Hẹn gặp lại (见) một lần nữa (再).'
      }
    ]
  },

  // =================== BÀI 3 ===================
  {
    lessonNumber: 3,
    title: 'Bài 3: Bạn tên là gì',
    hanziTitle: '你叫什么名字 (Nǐ jiào shénme míngzi)',
    description: 'Từ vựng hỏi tên, họ, thầy cô, xưng hô ngôi thứ 1 và 3',
    words: [
      {
        id: 'hsk1-3-01',
        hanzi: '叫',
        pinyin: 'jiào',
        vietnamese: 'gọi là / tên là / kêu',
        hanViet: 'Khiếu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 3: 你叫什么名字',
        source: 'hsk1',
        exampleSentence: '你叫什么名字？',
        examplePinyin: 'Nǐ jiào shénme míngzi?',
        exampleVietnamese: 'Bạn tên là gì?',
        radicals: '口 (khẩu) + 丩',
        mnemonic: 'Dùng miệng (口) cất tiếng kêu gọi (叫).'
      },
      {
        id: 'hsk1-3-02',
        hanzi: '什么',
        pinyin: 'shénme',
        vietnamese: 'gì / cái gì (đại từ nghi vấn)',
        hanViet: 'Thập ma',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 3: 你叫什么名字',
        source: 'hsk1',
        exampleSentence: '这是什么？',
        examplePinyin: 'Zhè shì shénme?',
        exampleVietnamese: 'Đây là cái gì?',
        radicals: '亻 (nhân) + 十 + 么',
        mnemonic: 'Người (亻) hỏi mười (十) câu chuyện gì.'
      },
      {
        id: 'hsk1-3-03',
        hanzi: '名字',
        pinyin: 'míngzi',
        vietnamese: 'tên / danh xưng',
        hanViet: 'Danh tự',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 3: 你叫什么名字',
        source: 'hsk1',
        exampleSentence: '我的名字叫大卫。',
        examplePinyin: 'Wǒ de míngzi jiào Dàwèi.',
        exampleVietnamese: 'Tên của tôi là David.',
        radicals: '名 (danh) + 字 (tự)',
        mnemonic: 'Buổi tối (夕) cất miệng (口) gọi tên (名).'
      },
      {
        id: 'hsk1-3-04',
        hanzi: '我',
        pinyin: 'wǒ',
        vietnamese: 'tôi / tao / mình (ngôi thứ nhất số ít)',
        hanViet: 'Ngã',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 3: 你叫什么名字',
        source: 'hsk1',
        exampleSentence: '我是中国人。',
        examplePinyin: 'Wǒ shì Zhōngguó rén.',
        exampleVietnamese: 'Tôi là người Trung Quốc.',
        radicals: '丿 + 戈 (vũ khí/giáo)',
        mnemonic: 'Tay cầm vũ khí (戈) bảo vệ cái tôi/bản thân (我).'
      },
      {
        id: 'hsk1-3-05',
        hanzi: '李月',
        pinyin: 'Lǐ Yuè',
        vietnamese: 'Lý Nguyệt (tên riêng người)',
        hanViet: 'Lý Nguyệt',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 3: 你叫什么名字',
        source: 'hsk1',
        exampleSentence: '她叫李月。',
        examplePinyin: 'Tā jiào Lǐ Yuè.',
        exampleVietnamese: 'Cô ấy tên là Lý Nguyệt.',
        radicals: '李 (họ Lý) + 月 (mặt trăng)',
        mnemonic: 'Họ Lý (李) sáng như vầng trăng (月).'
      },
      {
        id: 'hsk1-3-06',
        hanzi: '是',
        pinyin: 'shì',
        vietnamese: 'là / phải / đúng',
        hanViet: 'Thị',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 3: 你叫什么名字',
        source: 'hsk1',
        exampleSentence: '我是学生。',
        examplePinyin: 'Wǒ shì xuésheng.',
        exampleVietnamese: 'Tôi là học sinh.',
        radicals: '日 (mặt trời) + 疋 (chân)',
        mnemonic: 'Mặt trời (日) ngay thẳng chính là chân lý (是).'
      },
      {
        id: 'hsk1-3-07',
        hanzi: '老师',
        pinyin: 'lǎoshī',
        vietnamese: 'giáo viên / thầy giáo / cô giáo',
        hanViet: 'Lão sư',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 3: 你叫什么名字',
        source: 'hsk1',
        exampleSentence: '李老师是汉语老师。',
        examplePinyin: 'Lǐ lǎoshī shì Hànyǔ lǎoshī.',
        exampleVietnamese: 'Cô Lý là giáo viên tiếng Trung.',
        radicals: '老 (lão/già dặn) + 师 (thầy/sư)',
        mnemonic: 'Người thầy (师) kính trọng, uyên bác (老).'
      },
      {
        id: 'hsk1-3-08',
        hanzi: '吗',
        pinyin: 'ma',
        vietnamese: 'à / ư / hả / không? (trợ từ nghi vấn)',
        hanViet: 'Ma',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 3: 你叫什么名字',
        source: 'hsk1',
        exampleSentence: '你是老师吗？',
        examplePinyin: 'Nǐ shì lǎoshī ma?',
        exampleVietnamese: 'Bạn có phải là giáo viên không?',
        radicals: '口 (khẩu) + 马 (mã/ngựa)',
        mnemonic: 'Dùng miệng (口) cất tiếng hỏi (吗).'
      },
      {
        id: 'hsk1-3-09',
        hanzi: '学生',
        pinyin: 'xuésheng',
        vietnamese: 'học sinh / sinh viên',
        hanViet: 'Học sinh',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 3: 你叫什么名字',
        source: 'hsk1',
        exampleSentence: '我们都是学生。',
        examplePinyin: 'Wǒmen dōu shì xuésheng.',
        exampleVietnamese: 'Chúng tôi đều là học sinh.',
        radicals: '学 (học) + 生 (sinh)',
        mnemonic: 'Người sinh ra để học tập (学生).'
      },
      {
        id: 'hsk1-3-10',
        hanzi: '人',
        pinyin: 'rén',
        vietnamese: 'người / loài người',
        hanViet: 'Nhân',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 3: 你叫什么名字',
        source: 'hsk1',
        exampleSentence: '中国人，美国人，越南人。',
        examplePinyin: 'Zhōngguó rén, Měiguó rén, Yuènán rén.',
        exampleVietnamese: 'Người Trung Quốc, người Mỹ, người Việt Nam.',
        radicals: '人 (bộ nhân đứng)',
        mnemonic: 'Hình ảnh hai chân người đang đứng vững.'
      },
      {
        id: 'hsk1-3-11',
        hanzi: '中国',
        pinyin: 'Zhōngguó',
        vietnamese: 'Trung Quốc',
        hanViet: 'Trung Quốc',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 3: 你叫什么名字',
        source: 'hsk1',
        exampleSentence: '我喜欢中国。',
        examplePinyin: 'Wǒ xǐhuan Zhōngguó.',
        exampleVietnamese: 'Tôi thích Trung Quốc.',
        radicals: '中 (ở giữa) + 国 (quốc gia)',
        mnemonic: 'Đất nước (国) ở trung tâm (中).'
      },
      {
        id: 'hsk1-3-12',
        hanzi: '美国',
        pinyin: 'Měiguó',
        vietnamese: 'nước Mỹ / Hoa Kỳ',
        hanViet: 'Mỹ quốc',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 3: 你叫什么名字',
        source: 'hsk1',
        exampleSentence: '大卫是美国人。',
        examplePinyin: 'Dàwèi shì Měiguó rén.',
        exampleVietnamese: 'David là người Mỹ.',
        radicals: '美 (đẹp) + 国 (nước)',
        mnemonic: 'Mỹ quốc (美国).'
      }
    ]
  },

  // =================== BÀI 4 ===================
  {
    lessonNumber: 4,
    title: 'Bài 4: Cô ấy là giáo viên của tôi',
    hanziTitle: '她是我的汉语老师 (Tā shì wǒ de Hànyǔ lǎoshī)',
    description: 'Từ vựng cô ấy/anh ấy, chữ 的 (của), tiếng Hán, bạn học, bạn bè',
    words: [
      {
        id: 'hsk1-4-01',
        hanzi: '她',
        pinyin: 'tā',
        vietnamese: 'cô ấy / bà ấy / chị ấy (ngôi thứ ba giống cái)',
        hanViet: 'Tha',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 4: 她是我的汉语老师',
        source: 'hsk1',
        exampleSentence: '她是我的好朋友。',
        examplePinyin: 'Tā shì wǒ de hǎo péngyou.',
        exampleVietnamese: 'Cô ấy là bạn thân của tôi.',
        radicals: '女 (nữ) + 也 (dã)',
        mnemonic: 'Người phụ nữ (女) đó chính là Cô ấy (她).'
      },
      {
        id: 'hsk1-4-02',
        hanzi: '谁',
        pinyin: 'shéi / shuí',
        vietnamese: 'ai / người nào (đại từ nghi vấn)',
        hanViet: 'Thùy',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 4: 她是我的汉语老师',
        source: 'hsk1',
        exampleSentence: '他是谁？',
        examplePinyin: 'Tā shì shéi?',
        exampleVietnamese: 'Anh ấy là ai?',
        radicals: '讠 (ngôn) + 隹 (chuy)',
        mnemonic: 'Dùng lời nói (讠) để hỏi xem người đó là ai (谁).'
      },
      {
        id: 'hsk1-4-03',
        hanzi: '的',
        pinyin: 'de',
        vietnamese: 'của / trợ từ sở hữu hoặc định ngữ',
        hanViet: 'Đích',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 4: 她是我的汉语老师',
        source: 'hsk1',
        exampleSentence: '这是我的书。',
        examplePinyin: 'Zhè shì wǒ de shū.',
        exampleVietnamese: 'Đây là sách của tôi.',
        radicals: '白 (trắng) + 勺 (muỗng)',
        mnemonic: 'Mục tiêu đích đến màu trắng (白).'
      },
      {
        id: 'hsk1-4-04',
        hanzi: '汉语',
        pinyin: 'Hànyǔ',
        vietnamese: 'tiếng Trung / tiếng Hán',
        hanViet: 'Hán ngữ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 4: 她是我的汉语老师',
        source: 'hsk1',
        exampleSentence: '我会说汉语。',
        examplePinyin: 'Wǒ huì shuō Hànyǔ.',
        exampleVietnamese: 'Tôi biết nói tiếng Trung.',
        radicals: '汉 (Hán) + 语 (ngôn ngữ)',
        mnemonic: 'Ngôn ngữ (语) của người Hán (汉).'
      },
      {
        id: 'hsk1-4-05',
        hanzi: '哪',
        pinyin: 'nǎ',
        vietnamese: 'nào / ở đâu (đại từ nghi vấn)',
        hanViet: 'Nả',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 4: 她是我的汉语老师',
        source: 'hsk1',
        exampleSentence: '你是哪国人？',
        examplePinyin: 'Nǐ shì nǎ guó rén?',
        exampleVietnamese: 'Bạn là người nước nào?',
        radicals: '口 (khẩu) + 那 (kia)',
        mnemonic: 'Mở miệng (口) hỏi xem nơi nào (哪).'
      },
      {
        id: 'hsk1-4-06',
        hanzi: '国',
        pinyin: 'guó',
        vietnamese: 'nước / quốc gia',
        hanViet: 'Quốc',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 4: 她是我的汉语老师',
        source: 'hsk1',
        exampleSentence: '中国, 美国, 英国, 法国。',
        examplePinyin: 'Zhōngguó, Měiguó, Yīngguó, Fǎguó.',
        exampleVietnamese: 'Trung Quốc, Mỹ, Anh, Pháp.',
        radicals: '囗 (vi/khung bao quanh) + 玉 (ngọc)',
        mnemonic: 'Khung biên giới (囗) bao bọc viên ngọc quý (玉) của đất nước (国).'
      },
      {
        id: 'hsk1-4-07',
        hanzi: '同学',
        pinyin: 'tóngxué',
        vietnamese: 'bạn cùng lớp / bạn học',
        hanViet: 'Đồng học',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 4: 她是我的汉语老师',
        source: 'hsk1',
        exampleSentence: '他是我的大学同学。',
        examplePinyin: 'Tā shì wǒ de dàxué tóngxué.',
        exampleVietnamese: 'Cậu ấy là bạn học đại học của tôi.',
        radicals: '同 (cùng) + 学 (học)',
        mnemonic: 'Cùng nhau (同) học tập (学) tại một lớp.'
      },
      {
        id: 'hsk1-4-08',
        hanzi: '朋友',
        pinyin: 'péngyou',
        vietnamese: 'bạn bè / người bạn',
        hanViet: 'Bằng hữu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 4: 她是我的汉语老师',
        source: 'hsk1',
        exampleSentence: '我们是好朋友。',
        examplePinyin: 'Wǒmen shì hǎo péngyou.',
        exampleVietnamese: 'Chúng tôi là bạn tốt của nhau.',
        radicals: '朋 (bằng) + 友 (hữu)',
        mnemonic: 'Hai vầng trăng (月+月=朋) song hành cùng bàn tay nắm lấy nhau (友).'
      },
      {
        id: 'hsk1-4-09',
        hanzi: '他',
        pinyin: 'tā',
        vietnamese: 'anh ấy / ông ấy / hắn (ngôi thứ ba giống đực)',
        hanViet: 'Tha',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 4: 她是我的汉语老师',
        source: 'hsk1',
        exampleSentence: '他是我的同学。',
        examplePinyin: 'Tā shì wǒ de tóngxué.',
        exampleVietnamese: 'Cậu ấy là bạn cùng lớp của tôi.',
        radicals: '亻 (nhân) + 也 (dã)',
        mnemonic: 'Người đàn ông (亻) đó chính là Anh ấy (他).'
      }
    ]
  },

  // =================== BÀI 5 ===================
  {
    lessonNumber: 5,
    title: 'Bài 5: Con gái cô ấy năm nay 20 tuổi',
    hanziTitle: '她女儿今年二十岁 (Tā nǚ’ér jīnnián èrshí suì)',
    description: 'Từ vựng gia đình (gia, khẩu, nữ nhi), tuổi tác (tuế, kỉ, đa đại)',
    words: [
      {
        id: 'hsk1-5-01',
        hanzi: '家',
        pinyin: 'jiā',
        vietnamese: 'nhà / gia đình',
        hanViet: 'Gia',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 5: 她女儿今年二十岁',
        source: 'hsk1',
        exampleSentence: '你家有几口人？',
        examplePinyin: 'Nǐ jiā yǒu jǐ kǒu rén?',
        exampleVietnamese: 'Nhà bạn có mấy người?',
        radicals: '宀 (mái nhà) + 豕 (con heo/lợn)',
        mnemonic: 'Dưới mái nhà (宀) nuôi con lợn (豕) tạo thành mái ấm gia đình (家).'
      },
      {
        id: 'hsk1-5-02',
        hanzi: '有',
        pinyin: 'yǒu',
        vietnamese: 'có',
        hanViet: 'Hữu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 5: 她女儿今年二十岁',
        source: 'hsk1',
        exampleSentence: '我家有三口人。',
        examplePinyin: 'Wǒ jiā yǒu sān kǒu rén.',
        exampleVietnamese: 'Nhà tôi có 3 người.',
        radicals: '𠂇 (tay) + 月 (thịt)',
        mnemonic: 'Tay nắm giữ miếng thịt biểu thị sự sở hữu, có được (有).'
      },
      {
        id: 'hsk1-5-03',
        hanzi: '口',
        pinyin: 'kǒu',
        vietnamese: 'miệng / lượng từ đếm thành viên gia đình',
        hanViet: 'Khẩu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 5: 她女儿今年二十岁',
        source: 'hsk1',
        exampleSentence: '我家有四口人。',
        examplePinyin: 'Wǒ jiā yǒu sì kǒu rén.',
        exampleVietnamese: 'Nhà tôi có 4 miệng ăn/người.',
        radicals: '口 (bộ khẩu)',
        mnemonic: 'Hình cái miệng mở vuông vắn.'
      },
      {
        id: 'hsk1-5-04',
        hanzi: '女儿',
        pinyin: 'nǚ’ér',
        vietnamese: 'con gái',
        hanViet: 'Nữ nhi',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 5: 她女儿今年二十岁',
        source: 'hsk1',
        exampleSentence: '她女儿今年四岁。',
        examplePinyin: 'Tā nǚ’ér jīnnián sì suì.',
        exampleVietnamese: 'Con gái cô ấy năm nay 4 tuổi.',
        radicals: '女 (nữ) + 儿 (nhi)',
        mnemonic: 'Người con (儿) giới tính nữ (女).'
      },
      {
        id: 'hsk1-5-05',
        hanzi: '几',
        pinyin: 'jǐ',
        vietnamese: 'mấy / bao nhiêu (dưới 10)',
        hanViet: 'Kỷ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 5: 她女儿今年二十岁',
        source: 'hsk1',
        exampleSentence: '你女儿几岁了？',
        examplePinyin: 'Nǐ nǚ’ér jǐ suì le?',
        exampleVietnamese: 'Con gái bạn mấy tuổi rồi?',
        radicals: '几 (bộ kỷ)',
        mnemonic: 'Hình cái bàn nhỏ để hỏi số lượng ít.'
      },
      {
        id: 'hsk1-5-06',
        hanzi: '岁',
        pinyin: 'suì',
        vietnamese: 'tuổi',
        hanViet: 'Tuế',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 5: 她女儿今年二十岁',
        source: 'hsk1',
        exampleSentence: '我今年二十岁。',
        examplePinyin: 'Wǒ jīnnián èrshí suì.',
        exampleVietnamese: 'Tôi năm nay 20 tuổi.',
        radicals: '山 (núi) + 夕 (chiều tối)',
        mnemonic: 'Núi (山) trải qua bao buổi hoàng hôn (夕) tính theo năm tháng tuổi tác (岁).'
      },
      {
        id: 'hsk1-5-07',
        hanzi: '今年',
        pinyin: 'jīnnián',
        vietnamese: 'năm nay',
        hanViet: 'Kim niên',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 5: 她女儿今年二十岁',
        source: 'hsk1',
        exampleSentence: '今年是2026年。',
        examplePinyin: 'Jīnnián shì èr líng èr liù nián.',
        exampleVietnamese: 'Năm nay là năm 2026.',
        radicals: '今 (hiện tại) + 年 (năm)',
        mnemonic: 'Năm (年) ở hiện tại (今).'
      },
      {
        id: 'hsk1-5-08',
        hanzi: '多大',
        pinyin: 'duō dà',
        vietnamese: 'bao nhiêu tuổi (dùng cho người lớn)',
        hanViet: 'Đa đại',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 5: 她女儿今年二十岁',
        source: 'hsk1',
        exampleSentence: '李老师多大了？',
        examplePinyin: 'Lǐ lǎoshī duō dà le?',
        exampleVietnamese: 'Cô Lý bao nhiêu tuổi rồi?',
        radicals: '多 (nhiều) + 大 (lớn)',
        mnemonic: 'Hỏi độ lớn tuổi tác nhiều ít.'
      }
    ]
  },

  // =================== BÀI 6 ===================
  {
    lessonNumber: 6,
    title: 'Bài 6: Tôi biết nói tiếng Trung',
    hanziTitle: '我会说汉语 (Wǒ huì shuō Hànyǔ)',
    description: 'Từ vựng kỹ năng (hội, thuyết), nấu ăn (làm, đồ ăn TQ), ngon miệng, viết chữ Hán',
    words: [
      {
        id: 'hsk1-6-01',
        hanzi: '会',
        pinyin: 'huì',
        vietnamese: 'biết (thông qua học tập mà biết) / sẽ',
        hanViet: 'Hội',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 6: 我会说汉语',
        source: 'hsk1',
        exampleSentence: '我会写汉字。',
        examplePinyin: 'Wǒ huì xiě Hànzì.',
        exampleVietnamese: 'Tôi biết viết chữ Hán.',
        radicals: '人 (nhân) + 云 (vân)',
        mnemonic: 'Mọi người (人) tụ họp trao đổi lời nói (云) để tiếp thu kiến thức (会).'
      },
      {
        id: 'hsk1-6-02',
        hanzi: '说',
        pinyin: 'shuō',
        vietnamese: 'nói / phát biểu',
        hanViet: 'Thuyết',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 6: 我会说汉语',
        source: 'hsk1',
        exampleSentence: '你会说汉语吗？',
        examplePinyin: 'Nǐ huì shuō Hànyǔ ma?',
        exampleVietnamese: 'Bạn biết nói tiếng Trung không?',
        radicals: '讠 (ngôn) + 兑 (đoái)',
        mnemonic: 'Dùng lời nói (讠) làm vui lòng (兑) người nghe.'
      },
      {
        id: 'hsk1-6-03',
        hanzi: '妈妈',
        pinyin: 'māma',
        vietnamese: 'mẹ / má',
        hanViet: 'Ma ma',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 6: 我会说汉语',
        source: 'hsk1',
        exampleSentence: '我妈妈不会说英语。',
        examplePinyin: 'Wǒ māma bú huì shuō Yīngyǔ.',
        exampleVietnamese: 'Mẹ tôi không biết nói tiếng Anh.',
        radicals: '女 (nữ) + 马 (mã)',
        mnemonic: 'Người phụ nữ (女) hiền hậu vất vả chăm sóc con như ngựa (马).'
      },
      {
        id: 'hsk1-6-04',
        hanzi: '菜',
        pinyin: 'cài',
        vietnamese: 'món ăn / rau củ',
        hanViet: 'Thái',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 6: 我会说汉语',
        source: 'hsk1',
        exampleSentence: '中国菜很好吃。',
        examplePinyin: 'Zhōngguó cài hěn hǎochī.',
        exampleVietnamese: 'Món ăn Trung Quốc rất ngon.',
        radicals: '艹 (thảo) + 爫 + 木 (mộc)',
        mnemonic: 'Cây cỏ (艹) và hoa quả cây cối (木) hái về làm thành món ăn (菜).'
      },
      {
        id: 'hsk1-6-05',
        hanzi: '很',
        pinyin: 'hěn',
        vietnamese: 'rất / lắm (phó từ chỉ mức độ)',
        hanViet: 'Khẩn',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 6: 我会说汉语',
        source: 'hsk1',
        exampleSentence: '我很高兴。',
        examplePinyin: 'Wǒ hěn gāoxìng.',
        exampleVietnamese: 'Tôi rất vui.',
        radicals: '彳 (xích) + 艮 (cấn)',
        mnemonic: 'Bước chân (彳) kiên định (艮) vượt mức bình thường (很).'
      },
      {
        id: 'hsk1-6-06',
        hanzi: '好吃',
        pinyin: 'hǎochī',
        vietnamese: 'ngon / ngon miệng (thức ăn)',
        hanViet: 'Hảo cật',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 6: 我会说汉语',
        source: 'hsk1',
        exampleSentence: '这个苹果很好吃。',
        examplePinyin: 'Zhège píngguǒ hěn hǎochī.',
        exampleVietnamese: 'Quả táo này ăn rất ngon.',
        radicals: '好 (tốt) + 吃 (ăn)',
        mnemonic: 'Ăn vào (吃) thấy rất ngon miệng và thích thú (好).'
      },
      {
        id: 'hsk1-6-07',
        hanzi: '做',
        pinyin: 'zuò',
        vietnamese: 'làm / chế biến / nấu',
        hanViet: 'Tác',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 6: 我会说汉语',
        source: 'hsk1',
        exampleSentence: '你会做中国菜吗？',
        examplePinyin: 'Nǐ huì zuò Zhōngguó cài ma?',
        exampleVietnamese: 'Bạn biết nấu món ăn Trung Quốc không?',
        radicals: '亻 (nhân) + 古 (cổ) + 攵 (phác)',
        mnemonic: 'Con người (亻) dùng tay làm (攵) nên mọi thứ.'
      },
      {
        id: 'hsk1-6-08',
        hanzi: '写',
        pinyin: 'xiě',
        vietnamese: 'viết',
        hanViet: 'Tả',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 6: 我会说汉语',
        source: 'hsk1',
        exampleSentence: '我会写这个汉字。',
        examplePinyin: 'Wǒ huì xiě zhège Hànzì.',
        exampleVietnamese: 'Tôi biết viết chữ Hán này.',
        radicals: '冖 (mịch) + 与 (dữ)',
        mnemonic: 'Cầm bút viết chữ dưới mái hiên (冖).'
      },
      {
        id: 'hsk1-6-09',
        hanzi: '汉字',
        pinyin: 'Hànzì',
        vietnamese: 'chữ Hán',
        hanViet: 'Hán tự',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 6: 我会说汉语',
        source: 'hsk1',
        exampleSentence: '汉字很有意思。',
        examplePinyin: 'Hànzì hěn yǒu yìsi.',
        exampleVietnamese: 'Chữ Hán rất thú vị.',
        radicals: '汉 (Hán) + 字 (chữ)',
        mnemonic: 'Chữ viết (字) của dân tộc Hán (汉).'
      },
      {
        id: 'hsk1-6-10',
        hanzi: '字',
        pinyin: 'zì',
        vietnamese: 'chữ / tự',
        hanViet: 'Tự',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 6: 我会说汉语',
        source: 'hsk1',
        exampleSentence: '这个字怎么读？',
        examplePinyin: 'Zhège zì zěnme dú?',
        exampleVietnamese: 'Chữ này đọc như thế nào?',
        radicals: '宀 (mái nhà) + 子 (con)',
        mnemonic: 'Con cái (子) học chữ dưới mái nhà (宀).'
      },
      {
        id: 'hsk1-6-11',
        hanzi: '怎么',
        pinyin: 'zěnme',
        vietnamese: 'làm sao / như thế nào (hỏi cách thức)',
        hanViet: 'Chẩm ma',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 6: 我会说汉语',
        source: 'hsk1',
        exampleSentence: '这个汉字怎么写？',
        examplePinyin: 'Zhège Hànzì zěnme xiě?',
        exampleVietnamese: 'Chữ Hán này viết như thế nào?',
        radicals: '乍 + 心 (tâm) + 么',
        mnemonic: 'Trong lòng (心) tự hỏi phải làm sao.'
      },
      {
        id: 'hsk1-6-12',
        hanzi: '读',
        pinyin: 'dú',
        vietnamese: 'đọc / xem sách',
        hanViet: 'Độc',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 6: 我会说汉语',
        source: 'hsk1',
        exampleSentence: '请跟我读。',
        examplePinyin: 'Qǐng gēn wǒ dú.',
        exampleVietnamese: 'Xin hãy đọc theo tôi.',
        radicals: '讠 (ngôn) + 卖 (mại)',
        mnemonic: 'Dùng lời nói (讠) đọc to từng con chữ.'
      }
    ]
  },

  // =================== BÀI 7 ===================
  {
    lessonNumber: 7,
    title: 'Bài 7: Hôm nay là ngày mấy',
    hanziTitle: '今天几号 (Jīntiān jǐ hào)',
    description: 'Từ vựng thời gian, ngày tháng, hôm nay/ngày mai/hôm qua, trường học',
    words: [
      {
        id: 'hsk1-7-01',
        hanzi: '请',
        pinyin: 'qǐng',
        vietnamese: 'xin / mời / làm ơn',
        hanViet: 'Thỉnh',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 7: 今天几号',
        source: 'hsk1',
        exampleSentence: '请问，图书馆在哪儿？',
        examplePinyin: 'Qǐngwèn, túshūguǎn zài nǎr?',
        exampleVietnamese: 'Xin hỏi, thư viện ở đâu ạ?',
        radicals: '讠 (ngôn) + 青 (thanh)',
        mnemonic: 'Dùng lời nói (讠) trong sáng lịch sự (青) để mời/thỉnh (请).'
      },
      {
        id: 'hsk1-7-02',
        hanzi: '问',
        pinyin: 'wèn',
        vietnamese: 'hỏi',
        hanViet: 'Vấn',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 7: 今天几号',
        source: 'hsk1',
        exampleSentence: '我问你一个问题。',
        examplePinyin: 'Wǒ wèn nǐ yí ge wèntí.',
        exampleVietnamese: 'Tôi hỏi bạn một câu hỏi.',
        radicals: '门 (môn/cửa) + 口 (khẩu/miệng)',
        mnemonic: 'Đứng trước cửa (门) mở miệng (口) cất tiếng hỏi (问).'
      },
      {
        id: 'hsk1-7-03',
        hanzi: '今天',
        pinyin: 'jīntiān',
        vietnamese: 'hôm nay',
        hanViet: 'Kim thiên',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 7: 今天几号',
        source: 'hsk1',
        exampleSentence: '今天是星期一。',
        examplePinyin: 'Jīntiān shì xīngqīyī.',
        exampleVietnamese: 'Hôm nay là thứ Hai.',
        radicals: '今 (hiện tại) + 天 (trời/ngày)',
        mnemonic: 'Ngày (天) hiện tại (今).'
      },
      {
        id: 'hsk1-7-04',
        hanzi: '号',
        pinyin: 'hào',
        vietnamese: 'ngày (trong tháng) / số',
        hanViet: 'Hiệu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 7: 今天几号',
        source: 'hsk1',
        exampleSentence: '今天九月一号。',
        examplePinyin: 'Jīntiān jiǔ yuè yī hào.',
        exampleVietnamese: 'Hôm nay là ngày 1 tháng 9.',
        radicals: '口 (khẩu) + 丂',
        mnemonic: 'Số hiệu, ngày tháng trong tháng.'
      },
      {
        id: 'hsk1-7-05',
        hanzi: '月',
        pinyin: 'yuè',
        vietnamese: 'tháng / mặt trăng',
        hanViet: 'Nguyệt',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 7: 今天几号',
        source: 'hsk1',
        exampleSentence: '一年有十二个月。',
        examplePinyin: 'Yì nián yǒu shí’èr ge yuè.',
        exampleVietnamese: 'Một năm có 12 tháng.',
        radicals: '月 (bộ nguyệt)',
        mnemonic: 'Hình vành trăng khuyết chiếu sáng bầu trời.'
      },
      {
        id: 'hsk1-7-06',
        hanzi: '星期',
        pinyin: 'xīngqī',
        vietnamese: 'thứ / tuần lễ',
        hanViet: 'Tinh kỳ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 7: 今天几号',
        source: 'hsk1',
        exampleSentence: '星期天，星期日。',
        examplePinyin: 'Xīngqītiān, xīngqīrì.',
        exampleVietnamese: 'Chủ Nhật.',
        radicals: '星 (sao) + 期 (kỳ)',
        mnemonic: 'Chu kỳ (期) tuần hoàn theo các vì sao (星).'
      },
      {
        id: 'hsk1-7-07',
        hanzi: '昨天',
        pinyin: 'zuótiān',
        vietnamese: 'hôm qua',
        hanViet: 'Tạc thiên',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 7: 今天几号',
        source: 'hsk1',
        exampleSentence: '昨天是星期天。',
        examplePinyin: 'Zuótiān shì xīngqītiān.',
        exampleVietnamese: 'Hôm qua là Chủ Nhật.',
        radicals: '日 (mặt trời) + 乍 (chợt)',
        mnemonic: 'Mặt trời (日) của ngày vừa trôi qua.'
      },
      {
        id: 'hsk1-7-08',
        hanzi: '明天',
        pinyin: 'míngtiān',
        vietnamese: 'ngày mai',
        hanViet: 'Minh thiên',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 7: 今天几号',
        source: 'hsk1',
        exampleSentence: '明天见！',
        examplePinyin: 'Míngtiān jiàn!',
        exampleVietnamese: 'Mai gặp lại!',
        radicals: '明 (sáng/mặt trời + mặt trăng) + 天 (ngày)',
        mnemonic: 'Ngày (天) tươi sáng (明) ở tương lai phía trước.'
      },
      {
        id: 'hsk1-7-09',
        hanzi: '去',
        pinyin: 'qù',
        vietnamese: 'đi / tới',
        hanViet: 'Khứ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 7: 今天几号',
        source: 'hsk1',
        exampleSentence: '你去学校吗？',
        examplePinyin: 'Nǐ qù xuéxiào ma?',
        exampleVietnamese: 'Bạn đi đến trường không?',
        radicals: '土 (thổ) + 厶 (khư)',
        mnemonic: 'Rời khỏi mặt đất (土) di chuyển đi nơi khác (去).'
      },
      {
        id: 'hsk1-7-10',
        hanzi: '学校',
        pinyin: 'xuéxiào',
        vietnamese: 'trường học',
        hanViet: 'Học hiệu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 7: 今天几号',
        source: 'hsk1',
        exampleSentence: '我们的学校很大。',
        examplePinyin: 'Wǒmen de xuéxiào hěn dà.',
        exampleVietnamese: 'Trường của chúng tôi rất to lớn.',
        radicals: '学 (học) + 校 (trường)',
        mnemonic: 'Nơi (校) tụ hội để học tập (学).'
      },
      {
        id: 'hsk1-7-11',
        hanzi: '看',
        pinyin: 'kàn',
        vietnamese: 'nhìn / xem / đọc (sách) / thăm',
        hanViet: 'Khán',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 7: 今天几号',
        source: 'hsk1',
        exampleSentence: '我在看书。',
        examplePinyin: 'Wǒ zài kàn shū.',
        exampleVietnamese: 'Tôi đang đọc sách.',
        radicals: '手 (tay) + 目 (mắt)',
        mnemonic: 'Đưa bàn tay (手) che lên trên mắt (目) để phóng tầm mắt nhìn/xem (看).'
      },
      {
        id: 'hsk1-7-12',
        hanzi: '书',
        pinyin: 'shū',
        vietnamese: 'sách / quyển sách',
        hanViet: 'Thư',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 7: 今天几号',
        source: 'hsk1',
        exampleSentence: '一本汉语书。',
        examplePinyin: 'Yì běn Hànyǔ shū.',
        exampleVietnamese: 'Một cuốn sách tiếng Trung.',
        radicals: '乛 + 亅 + 丶',
        mnemonic: 'Hình ảnh chồng sách mở ra để đọc.'
      }
    ]
  },

  // =================== BÀI 8 ===================
  {
    lessonNumber: 8,
    title: 'Bài 8: Tôi muốn uống trà',
    hanziTitle: '我想喝茶 (Wǒ xiǎng hē chá)',
    description: 'Từ vựng đồ ăn thức uống (trà, nước, cơm), mua sắm, giá tiền (khối, bao nhiêu tiền)',
    words: [
      {
        id: 'hsk1-8-01',
        hanzi: '想',
        pinyin: 'xiǎng',
        vietnamese: 'muốn / nghĩ / nhớ',
        hanViet: 'Tưởng',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '我想喝水。',
        examplePinyin: 'Wǒ xiǎng hē shuǐ.',
        exampleVietnamese: 'Tôi muốn uống nước.',
        radicals: '相 (tương) + 心 (tâm)',
        mnemonic: 'Tâm trí (心) suy nghĩ và tưởng tượng (想).'
      },
      {
        id: 'hsk1-8-02',
        hanzi: '喝',
        pinyin: 'hē',
        vietnamese: 'uống',
        hanViet: 'Hát',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '你想喝什么？',
        examplePinyin: 'Nǐ xiǎng hē shénme?',
        exampleVietnamese: 'Bạn muốn uống cái gì?',
        radicals: '口 (miệng) + 曷',
        mnemonic: 'Mở miệng (口) uống nước vào trong.'
      },
      {
        id: 'hsk1-8-03',
        hanzi: '茶',
        pinyin: 'chá',
        vietnamese: 'trà / chè',
        hanViet: 'Trà',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '请喝茶！',
        examplePinyin: 'Qǐng hē chá!',
        exampleVietnamese: 'Mời uống trà!',
        radicals: '艹 (thảo) + 人 (người) + 木 (mộc)',
        mnemonic: 'Lá cây (艹) từ loài cây (木) con người (人) hái về pha trà (茶).'
      },
      {
        id: 'hsk1-8-04',
        hanzi: '吃',
        pinyin: 'chī',
        vietnamese: 'ăn',
        hanViet: 'Cật',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '你想吃米饭吗？',
        examplePinyin: 'Nǐ xiǎng chī mǐfàn ma?',
        exampleVietnamese: 'Bạn muốn ăn cơm không?',
        radicals: '口 (miệng) + 乞 (khất)',
        mnemonic: 'Đưa đồ ăn vào miệng (口) để thưởng thức (吃).'
      },
      {
        id: 'hsk1-8-05',
        hanzi: '米饭',
        pinyin: 'mǐfàn',
        vietnamese: 'cơm trắng',
        hanViet: 'Mễ phạn',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '吃米饭。',
        examplePinyin: 'Chī mǐfàn.',
        exampleVietnamese: 'Ăn cơm.',
        radicals: '米 (gạo) + 饭 (cơm)',
        mnemonic: 'Hạt gạo (米) nấu chín thành cơm (饭).'
      },
      {
        id: 'hsk1-8-06',
        hanzi: '下午',
        pinyin: 'xiàwǔ',
        vietnamese: 'buổi chiều',
        hanViet: 'Hạ ngọ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '下午我去商店。',
        examplePinyin: 'Xiàwǔ wǒ qù shāngdiàn.',
        exampleVietnamese: 'Buổi chiều tôi đi đến cửa hàng.',
        radicals: '下 (dưới/sau) + 午 (ngọ)',
        mnemonic: 'Thời gian sau buổi trưa (午).'
      },
      {
        id: 'hsk1-8-07',
        hanzi: '商店',
        pinyin: 'shāngdiàn',
        vietnamese: 'cửa hàng / tiệm tạp hóa',
        hanViet: 'Thương điếm',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '这个商店很大。',
        examplePinyin: 'Zhège shāngdiàn hěn dà.',
        exampleVietnamese: 'Cửa hàng này rất to.',
        radicals: '商 (thương mại) + 店 (tiệm/quán)',
        mnemonic: 'Tiệm (店) buôn bán kinh doanh (商).'
      },
      {
        id: 'hsk1-8-08',
        hanzi: '买',
        pinyin: 'mǎi',
        vietnamese: 'mua',
        hanViet: 'Mãi',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '你想买什么？',
        examplePinyin: 'Nǐ xiǎng mǎi shénme?',
        exampleVietnamese: 'Bạn muốn mua gì?',
        radicals: '乛 + 头',
        mnemonic: 'Mua sắm đồ vật.'
      },
      {
        id: 'hsk1-8-09',
        hanzi: '个',
        pinyin: 'ge',
        vietnamese: 'cái / con / người (lượng từ phổ biến nhất)',
        hanViet: 'Cá',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '一个人，一个杯子。',
        examplePinyin: 'Yí ge rén, yí ge bēizi.',
        exampleVietnamese: 'Một người, một chiếc cốc.',
        radicals: '人 (nhân) + 丨',
        mnemonic: 'Lượng từ đếm đồ vật đơn lẻ.'
      },
      {
        id: 'hsk1-8-10',
        hanzi: '杯子',
        pinyin: 'bēizi',
        vietnamese: 'chiếc cốc / ly / tách',
        hanViet: 'Bôi tử',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '这个杯子多少钱？',
        examplePinyin: 'Zhège bēizi duōshao qián?',
        exampleVietnamese: 'Chiếc ly này bao nhiêu tiền?',
        radicals: '木 (mộc) + 不 + 子',
        mnemonic: 'Chiếc cốc (杯) dùng để uống nước.'
      },
      {
        id: 'hsk1-8-11',
        hanzi: '这',
        pinyin: 'zhè',
        vietnamese: 'đây / này (đại từ chỉ định gần)',
        hanViet: 'Giá',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '这是我的杯子。',
        examplePinyin: 'Zhè shì wǒ de bēizi.',
        exampleVietnamese: 'Đây là cốc của tôi.',
        radicals: '辶 (quai xước) + 文 (văn)',
        mnemonic: 'Chỉ vật ở vị trí gần ngay trước mặt (这).'
      },
      {
        id: 'hsk1-8-12',
        hanzi: '多少',
        pinyin: 'duōshao',
        vietnamese: 'bao nhiêu (hỏi số lượng nhiều hoặc giá tiền)',
        hanViet: 'Đa thiểu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '多少钱？',
        examplePinyin: 'Duōshao qián?',
        exampleVietnamese: 'Bao nhiêu tiền?',
        radicals: '多 (nhiều) + 少 (ít)',
        mnemonic: 'Hỏi xem số lượng nhiều (多) hay ít (少).'
      },
      {
        id: 'hsk1-8-13',
        hanzi: '钱',
        pinyin: 'qián',
        vietnamese: 'tiền',
        hanViet: 'Tiền',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '十块钱。',
        examplePinyin: 'Shí kuài qián.',
        exampleVietnamese: '10 tệ.',
        radicals: '钅 (kim/tiền tệ kim loại) + 戋',
        mnemonic: 'Kim loại quý (钅) đúc thành tiền tệ (钱).'
      },
      {
        id: 'hsk1-8-14',
        hanzi: '块',
        pinyin: 'kuài',
        vietnamese: 'đồng / tệ (đơn vị tiền tệ khẩu ngữ)',
        hanViet: 'Khối',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '十五块。',
        examplePinyin: 'Shíwǔ kuài.',
        exampleVietnamese: '15 đồng/tệ.',
        radicals: '土 (thổ) + 夬',
        mnemonic: 'Khối tiền tệ.'
      },
      {
        id: 'hsk1-8-15',
        hanzi: '那',
        pinyin: 'nà',
        vietnamese: 'đó / kia (đại từ chỉ định xa)',
        hanViet: 'Na',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 8: 我想喝茶',
        source: 'hsk1',
        exampleSentence: '那个杯子十八块。',
        examplePinyin: 'Nà ge bēizi shíbā kuài.',
        exampleVietnamese: 'Chiếc cốc kia 18 tệ.',
        radicals: '刀 + 二 + 阝 (ấp)',
        mnemonic: 'Chỉ vào vật ở phía xa (那).'
      }
    ]
  },

  // =================== BÀI 9 ===================
  {
    lessonNumber: 9,
    title: 'Bài 9: Con trai bạn làm việc ở đâu',
    hanziTitle: '你儿子在哪儿工作 (Nǐ érzi zài nǎr gōngzuò)',
    description: 'Từ vựng về địa điểm, phương hướng, nghề nghiệp và nơi chốn',
    words: [
      {
        id: 'hsk1-9-01',
        hanzi: '小',
        pinyin: 'xiǎo',
        vietnamese: 'nhỏ / bé / xíu',
        hanViet: 'Tiểu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '小猫很可爱。',
        examplePinyin: 'Xiǎo māo hěn kě\'ài.',
        exampleVietnamese: 'Chú mèo con rất đáng yêu.',
        radicals: '小 (tiểu)',
        mnemonic: 'Nét sổ chia tách sang 2 bên thành các hạt nhỏ xíu.'
      },
      {
        id: 'hsk1-9-02',
        hanzi: '猫',
        pinyin: 'māo',
        vietnamese: 'con mèo',
        hanViet: 'Miêu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '小猫在哪儿？',
        examplePinyin: 'Xiǎo māo zài nǎr?',
        exampleVietnamese: 'Con mèo con ở đâu?',
        radicals: '犭 (khuyển/loài thú) + 苗 (miêu/cây mạ)',
        mnemonic: 'Loài thú cưng (犭) rình mồi trên đồng mạ (苗) kêu meo meo.'
      },
      {
        id: 'hsk1-9-03',
        hanzi: '在',
        pinyin: 'zài',
        vietnamese: 'ở / tại / đang',
        hanViet: 'Tại',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '小猫在椅子下面。',
        examplePinyin: 'Xiǎo māo zài yǐzi xiàmiàn.',
        exampleVietnamese: 'Mèo con ở dưới gầm ghế.',
        radicals: '𠂇 + 土 (thổ/đất)',
        mnemonic: 'Bàn tay dựng một cọc mốc trên mảnh đất (土) biểu thị vị trí tồn tại.'
      },
      {
        id: 'hsk1-9-04',
        hanzi: '那儿',
        pinyin: 'nàr',
        vietnamese: 'ở đó / chỗ kia',
        hanViet: 'Na nhi',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '小狗在那儿。',
        examplePinyin: 'Xiǎo gǒu zài nàr.',
        exampleVietnamese: 'Chú chó con ở đằng kia.',
        radicals: '那 + 儿',
        mnemonic: 'Chỉ về vị trí xa người nói.'
      },
      {
        id: 'hsk1-9-05',
        hanzi: '狗',
        pinyin: 'gǒu',
        vietnamese: 'con chó',
        hanViet: 'Cẩu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '那是一只小狗。',
        examplePinyin: 'Nà shì yì zhī xiǎo gǒu.',
        exampleVietnamese: 'Đó là một chú chó con.',
        radicals: '犭 (khuyển) + 句 (cú)',
        mnemonic: 'Loài động vật 4 chân (犭) sủa gâu gâu từng câu (句).'
      },
      {
        id: 'hsk1-9-06',
        hanzi: '椅子',
        pinyin: 'yǐzi',
        vietnamese: 'cái ghế',
        hanViet: 'Ỷ tử',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '椅子在哪儿？',
        examplePinyin: 'Yǐzi zài nǎr?',
        exampleVietnamese: 'Cái ghế ở đâu?',
        radicals: '木 (mộc) + 奇 + 子',
        mnemonic: 'Chiếc ghế làm từ gỗ (木) có hình dáng độc đáo.'
      },
      {
        id: 'hsk1-9-07',
        hanzi: '下面',
        pinyin: 'xiàmiàn',
        vietnamese: 'phía dưới / bên dưới / dưới gầm',
        hanViet: 'Hạ diện',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '在椅子下面。',
        examplePinyin: 'Zài yǐzi xiàmiàn.',
        exampleVietnamese: 'Ở dưới gầm ghế.',
        radicals: '下 (dưới) + 面 (mặt/diện)',
        mnemonic: 'Mặt phẳng nằm ở phía dưới.'
      },
      {
        id: 'hsk1-9-08',
        hanzi: '哪儿',
        pinyin: 'nǎr',
        vietnamese: 'ở đâu / chỗ nào',
        hanViet: 'Nả nhi',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '你在哪儿工作？',
        examplePinyin: 'Nǐ zài nǎr gōngzuò?',
        exampleVietnamese: 'Bạn làm việc ở đâu?',
        radicals: '哪 + 儿',
        mnemonic: 'Mở miệng (口) hỏi địa điểm ở đâu.'
      },
      {
        id: 'hsk1-9-09',
        hanzi: '工作',
        pinyin: 'gōngzuò',
        vietnamese: 'làm việc / công việc',
        hanViet: 'Công tác',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '我在学校工作。',
        examplePinyin: 'Wǒ zài xuéxiào gōngzuò.',
        exampleVietnamese: 'Tôi làm việc ở trường học.',
        radicals: '工 (công thợ) + 亻 (nhân) + 乍',
        mnemonic: 'Người (亻) dùng công cụ lao động (工) tạo ra công việc.'
      },
      {
        id: 'hsk1-9-10',
        hanzi: '儿子',
        pinyin: 'érzi',
        vietnamese: 'con trai',
        hanViet: 'Nhi tử',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '我儿子是医生。',
        examplePinyin: 'Wǒ érzi shì yīshēng.',
        exampleVietnamese: 'Con trai tôi là bác sĩ.',
        radicals: '儿 (nhi) + 子 (tử)',
        mnemonic: 'Hình ảnh đứa con trai bé bỏng.'
      },
      {
        id: 'hsk1-9-11',
        hanzi: '医院',
        pinyin: 'yīyuàn',
        vietnamese: 'bệnh viện',
        hanViet: 'Y viện',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '他在医院工作。',
        examplePinyin: 'Tā zài yīyuàn gōngzuò.',
        exampleVietnamese: 'Anh ấy làm việc ở bệnh viện.',
        radicals: '医 (y học) + 院 (khu viện)',
        mnemonic: 'Nơi tập hợp các bác sĩ y khoa chữa bệnh.'
      },
      {
        id: 'hsk1-9-12',
        hanzi: '医生',
        pinyin: 'yīshēng',
        vietnamese: 'bác sĩ',
        hanViet: 'Y sinh',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '我爸爸是医生。',
        examplePinyin: 'Wǒ bàba shì yīshēng.',
        exampleVietnamese: 'Bố tôi là bác sĩ.',
        radicals: '医 (y) + 生 (người/sinh)',
        mnemonic: 'Người hành nghề cứu sống (生) bệnh nhân bằng y thuật (医).'
      },
      {
        id: 'hsk1-9-13',
        hanzi: '爸爸',
        pinyin: 'bàba',
        vietnamese: 'bố / cha / ba',
        hanViet: 'Ba ba',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 9: 你儿子在哪儿工作',
        source: 'hsk1',
        exampleSentence: '我爱我爸爸。',
        examplePinyin: 'Wǒ ài wǒ bàba.',
        exampleVietnamese: 'Tôi yêu bố tôi.',
        radicals: '父 (phụ/người cha) + 巴',
        mnemonic: 'Người cha (父) che chở cho cả gia đình.'
      }
    ]
  },

  // =================== BÀI 10 ===================
  {
    lessonNumber: 10,
    title: 'Bài 10: Tôi có thể ngồi đây không',
    hanziTitle: '我能坐这儿吗 (Wǒ néng zuò zhèr ma)',
    description: 'Từ vựng về bàn ghế, vị trí phương hướng trước sau, khả năng và xin phép',
    words: [
      {
        id: 'hsk1-10-01',
        hanzi: '桌子',
        pinyin: 'zhuōzi',
        vietnamese: 'cái bàn',
        hanViet: 'Trác tử',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 10: 我能坐这儿吗',
        source: 'hsk1',
        exampleSentence: '桌子上有一本书。',
        examplePinyin: 'Zhuōzi shang yǒu yì běn shū.',
        exampleVietnamese: 'Trên bàn có một quyển sách.',
        radicals: '木 (mộc/gỗ) + 卓 + 子',
        mnemonic: 'Chiếc bàn làm bằng chất liệu gỗ (木).'
      },
      {
        id: 'hsk1-10-02',
        hanzi: '上面',
        pinyin: 'shàngmiàn',
        vietnamese: 'phía trên / bên trên / trên mặt',
        hanViet: 'Thượng diện',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 10: 我能坐这儿吗',
        source: 'hsk1',
        exampleSentence: '电脑在桌子上面。',
        examplePinyin: 'Diànnǎo zài zhuōzi shàngmiàn.',
        exampleVietnamese: 'Máy tính ở trên bàn.',
        radicals: '上 (trên) + 面 (mặt)',
        mnemonic: 'Vị trí ở mặt bên trên.'
      },
      {
        id: 'hsk1-10-03',
        hanzi: '电脑',
        pinyin: 'diànnǎo',
        vietnamese: 'máy vi tính',
        hanViet: 'Điện não',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 10: 我能坐这儿吗',
        source: 'hsk1',
        exampleSentence: '这是我的电脑。',
        examplePinyin: 'Zhè shì wǒ de diànnǎo.',
        exampleVietnamese: 'Đây là máy tính của tôi.',
        radicals: '电 (điện) + 脑 (não bộ)',
        mnemonic: 'Bộ não (脑) hoạt động bằng điện (电).'
      },
      {
        id: 'hsk1-10-04',
        hanzi: '和',
        pinyin: 'hé',
        vietnamese: 'và / cùng với',
        hanViet: 'Hòa',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 10: 我能坐这儿吗',
        source: 'hsk1',
        exampleSentence: '我和他是好朋友。',
        examplePinyin: 'Wǒ hé tā shì hǎo péngyou.',
        exampleVietnamese: 'Tôi và anh ấy là bạn tốt.',
        radicals: '禾 (lúa) + 口 (miệng)',
        mnemonic: 'Có thóc lúa (禾) để cho vào miệng (口) thì mọi người hòa thuận (和) bên nhau.'
      },
      {
        id: 'hsk1-10-05',
        hanzi: '本',
        pinyin: 'běn',
        vietnamese: 'quyển / cuốn (lượng từ của sách)',
        hanViet: 'Bản',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 10: 我能坐这儿吗',
        source: 'hsk1',
        exampleSentence: '三本书。',
        examplePinyin: 'Sān běn shū.',
        exampleVietnamese: 'Ba quyển sách.',
        radicals: '木 (gỗ) + 一 (nét gạch dưới gốc)',
        mnemonic: 'Gốc rễ thân cây gỗ (木) làm thành giấy in sách (本).'
      },
      {
        id: 'hsk1-10-06',
        hanzi: '里',
        pinyin: 'lǐ',
        vietnamese: 'trong / bên trong',
        hanViet: 'Lý',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 10: 我能坐这儿吗',
        source: 'hsk1',
        exampleSentence: '书在包里。',
        examplePinyin: 'Shū zài bāo lǐ.',
        exampleVietnamese: 'Sách ở trong túi.',
        radicals: '田 (ruộng) + 土 (đất)',
        mnemonic: 'Bên trong làng quê có ruộng (田) và đất (土).'
      },
      {
        id: 'hsk1-10-07',
        hanzi: '前面',
        pinyin: 'qiánmiàn',
        vietnamese: 'phía trước / đằng trước',
        hanViet: 'Tiền diện',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 10: 我能坐这儿吗',
        source: 'hsk1',
        exampleSentence: '前面那个人是谁？',
        examplePinyin: 'Qiánmiàn nà ge rén shì shéi?',
        exampleVietnamese: 'Người ở phía trước kia là ai?',
        radicals: '前 (trước) + 面 (mặt)',
        mnemonic: 'Vị trí ở phía trước mặt.'
      },
      {
        id: 'hsk1-10-08',
        hanzi: '后面',
        pinyin: 'hòumiàn',
        vietnamese: 'phía sau / đằng sau',
        hanViet: 'Hậu diện',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 10: 我能坐这儿吗',
        source: 'hsk1',
        exampleSentence: '后面是学校。',
        examplePinyin: 'Hòumiàn shì xuéxiào.',
        exampleVietnamese: 'Đằng sau là trường học.',
        radicals: '后 (sau) + 面 (mặt)',
        mnemonic: 'Vị trí ở phía sau lưng.'
      },
      {
        id: 'hsk1-10-09',
        hanzi: '这儿',
        pinyin: 'zhèr',
        vietnamese: 'ở đây / chỗ này',
        hanViet: 'Giá nhi',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 10: 我能坐这儿吗',
        source: 'hsk1',
        exampleSentence: '这儿有人吗？',
        examplePinyin: 'Zhèr yǒu rén ma?',
        exampleVietnamese: 'Chỗ này có ai không?',
        radicals: '这 + 儿',
        mnemonic: 'Chỉ vào vị trí ngay gần người nói.'
      },
      {
        id: 'hsk1-10-10',
        hanzi: '没有',
        pinyin: 'méiyǒu',
        vietnamese: 'không có / chưa',
        hanViet: 'Một hữu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 10: 我能坐这儿吗',
        source: 'hsk1',
        exampleSentence: '这儿没有人。',
        examplePinyin: 'Zhèr méiyǒu rén.',
        exampleVietnamese: 'Ở đây không có người.',
        radicals: '没 + 有',
        mnemonic: 'Dạng phủ định của 有 (có).'
      },
      {
        id: 'hsk1-10-11',
        hanzi: '能',
        pinyin: 'néng',
        vietnamese: 'có thể / có khả năng',
        hanViet: 'Năng',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 10: 我能坐这儿吗',
        source: 'hsk1',
        exampleSentence: '我能坐这儿吗？',
        examplePinyin: 'Wǒ néng zuò zhèr ma?',
        exampleVietnamese: 'Tôi có thể ngồi ở đây không?',
        radicals: '厶 + 月 + 匕 + 匕',
        mnemonic: 'Năng lực (能) mạnh mẽ của chú gấu dũng mãnh.'
      },
      {
        id: 'hsk1-10-12',
        hanzi: '坐',
        pinyin: 'zuò',
        vietnamese: 'ngồi / đi (xe, tàu, máy bay)',
        hanViet: 'Tọa',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 10: 我能坐这儿吗',
        source: 'hsk1',
        exampleSentence: '请坐！',
        examplePinyin: 'Qǐng zuò!',
        exampleVietnamese: 'Mời ngồi!',
        radicals: '人 (người) + 人 (người) + 土 (đất)',
        mnemonic: 'Hai người (人 人) cùng ngồi đàm đạo trên mặt đất (土).'
      }
    ]
  },

  // =================== BÀI 11 ===================
  {
    lessonNumber: 11,
    title: 'Bài 11: Bây giờ là mấy giờ',
    hanziTitle: '现在几点 (Xiànzài jǐ diǎn)',
    description: 'Từ vựng về thời gian, giờ giấc, phút, các buổi trong ngày và sinh hoạt',
    words: [
      {
        id: 'hsk1-11-01',
        hanzi: '现在',
        pinyin: 'xiànzài',
        vietnamese: 'bây giờ / hiện tại',
        hanViet: 'Hiện tại',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 11: 现在几点',
        source: 'hsk1',
        exampleSentence: '现在十点十分。',
        examplePinyin: 'Xiànzài shí diǎn shí fēn.',
        exampleVietnamese: 'Bây giờ là 10 giờ 10 phút.',
        radicals: '现 (hiện) + 在 (tại)',
        mnemonic: 'Khoảnh khắc tồn tại ngay lúc này.'
      },
      {
        id: 'hsk1-11-02',
        hanzi: '点',
        pinyin: 'diǎn',
        vietnamese: 'giờ / tiếng (đồng hồ) / điểm',
        hanViet: 'Điểm',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 11: 现在几点',
        source: 'hsk1',
        exampleSentence: '现在几点？',
        examplePinyin: 'Xiànzài jǐ diǎn?',
        exampleVietnamese: 'Bây giờ là mấy giờ?',
        radicals: '占 + 灬 (hỏa)',
        mnemonic: 'Kim đồng hồ chỉ đúng từng điểm (点) mốc giờ.'
      },
      {
        id: 'hsk1-11-03',
        hanzi: '分',
        pinyin: 'fēn',
        vietnamese: 'phút (thời gian) / chia',
        hanViet: 'Phân',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 11: 现在几点',
        source: 'hsk1',
        exampleSentence: '八点五分。',
        examplePinyin: 'Bā diǎn wǔ fēn.',
        exampleVietnamese: '8 giờ 5 phút.',
        radicals: '八 (bát) + 刀 (đao)',
        mnemonic: 'Dùng dao (刀) chia cắt từng phần (分) nhỏ.'
      },
      {
        id: 'hsk1-11-04',
        hanzi: '中午',
        pinyin: 'zhōngwǔ',
        vietnamese: 'buổi trưa (khoảng 11h - 13h)',
        hanViet: 'Trung ngọ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 11: 现在几点',
        source: 'hsk1',
        exampleSentence: '中午几点吃饭？',
        examplePinyin: 'Zhōngwǔ jǐ diǎn chī fàn?',
        exampleVietnamese: 'Buổi trưa mấy giờ ăn cơm?',
        radicals: '中 (ở giữa) + 午 (giờ ngọ)',
        mnemonic: 'Chính giữa (中) của một ngày lúc giờ ngọ (午).'
      },
      {
        id: 'hsk1-11-05',
        hanzi: '吃饭',
        pinyin: 'chī fàn',
        vietnamese: 'ăn cơm / dùng bữa',
        hanViet: 'Ngật phạn',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 11: 现在几点',
        source: 'hsk1',
        exampleSentence: '我们十二点吃饭。',
        examplePinyin: 'Wǒmen shí\'èr diǎn chī fàn.',
        exampleVietnamese: 'Chúng tôi 12 giờ ăn cơm.',
        radicals: '吃 (ăn) + 饭 (cơm)',
        mnemonic: 'Mở miệng ăn thức ăn ngon.'
      },
      {
        id: 'hsk1-11-06',
        hanzi: '时候',
        pinyin: 'shíhou',
        vietnamese: 'lúc / khi / thời điểm',
        hanViet: 'Thời hậu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 11: 现在几点',
        source: 'hsk1',
        exampleSentence: '什么时候回学校？',
        examplePinyin: 'Shénme shíhou huí xuéxiào?',
        exampleVietnamese: 'Khi nào quay về trường?',
        radicals: '时 (thời) + 候 (hậu)',
        mnemonic: 'Khoảng thời gian chờ đợi.'
      },
      {
        id: 'hsk1-11-07',
        hanzi: '回',
        pinyin: 'huí',
        vietnamese: 'về / quay lại / trở lại',
        hanViet: 'Hồi',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 11: 现在几点',
        source: 'hsk1',
        exampleSentence: '我下午五点回家。',
        examplePinyin: 'Wǒ xiàwǔ wǔ diǎn huí jiā.',
        exampleVietnamese: '5 giờ chiều tôi về nhà.',
        radicals: '囗 (vi bao quanh) + 口 (khẩu)',
        mnemonic: 'Hình ảnh vòng xoáy xoay tròn quay trở về điểm xuất phát.'
      },
      {
        id: 'hsk1-11-08',
        hanzi: '我们',
        pinyin: 'wǒmen',
        vietnamese: 'chúng tôi / chúng ta',
        hanViet: 'Ngã môn',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 11: 现在几点',
        source: 'hsk1',
        exampleSentence: '我们一起去看电影吧。',
        examplePinyin: 'Wǒmen yìqǐ qù kàn diànyǐng ba.',
        exampleVietnamese: 'Chúng ta cùng đi xem phim nhé.',
        radicals: '我 (tôi) + 们 (số nhiều)',
        mnemonic: 'Ghép từ 我 và hậu tố 们.'
      },
      {
        id: 'hsk1-11-09',
        hanzi: '电影',
        pinyin: 'diànyǐng',
        vietnamese: 'phim / điện ảnh',
        hanViet: 'Điện ảnh',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 11: 现在几点',
        source: 'hsk1',
        exampleSentence: '我想看电影。',
        examplePinyin: 'Wǒ xiǎng kàn diànyǐng.',
        exampleVietnamese: 'Tôi muốn xem phim.',
        radicals: '电 (điện) + 影 (hình bóng)',
        mnemonic: 'Hình bóng (影) chuyển động nhờ ánh sáng của dòng điện (电).'
      },
      {
        id: 'hsk1-11-10',
        hanzi: '住',
        pinyin: 'zhù',
        vietnamese: 'sống / ở / cư trú',
        hanViet: 'Trú',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 11: 现在几点',
        source: 'hsk1',
        exampleSentence: '你在北京住几天？',
        examplePinyin: 'Nǐ zài Běijīng zhù jǐ tiān?',
        exampleVietnamese: 'Bạn ở Bắc Kinh mấy ngày?',
        radicals: '亻 (nhân) + 主 (chủ)',
        mnemonic: 'Người (亻) làm chủ (主) căn nhà mình sinh sống (住).'
      },
      {
        id: 'hsk1-11-11',
        hanzi: '前',
        pinyin: 'qián',
        vietnamese: 'trước / trước đây',
        hanViet: 'Tiền',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 11: 现在几点',
        source: 'hsk1',
        exampleSentence: '五天前。',
        examplePinyin: 'Wǔ tiān qián.',
        exampleVietnamese: '5 ngày trước.',
        radicals: '䒑 + 月 + 刂',
        mnemonic: 'Khoảng thời gian về trước.'
      }
    ]
  },

  // =================== BÀI 12 ===================
  {
    lessonNumber: 12,
    title: 'Bài 12: Thời tiết ngày mai thế nào',
    hanziTitle: '明天天气怎么样 (Míngtiān tiānqì zěnmeyàng)',
    description: 'Từ vựng về thời tiết nóng lạnh, mưa, sức khỏe và hoa quả',
    words: [
      {
        id: 'hsk1-12-01',
        hanzi: '天气',
        pinyin: 'tiānqì',
        vietnamese: 'thời tiết',
        hanViet: 'Thiên khí',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '今天天气很好。',
        examplePinyin: 'Jīntiān tiānqì hěn hǎo.',
        exampleVietnamese: 'Hôm nay thời tiết rất đẹp.',
        radicals: '天 (trời) + 气 (khí)',
        mnemonic: 'Bầu không khí (气) của bầu trời (天).'
      },
      {
        id: 'hsk1-12-02',
        hanzi: '怎么样',
        pinyin: 'zěnmeyàng',
        vietnamese: 'thế nào / ra sao',
        hanViet: 'Chẩm ma dạng',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '北京天气怎么样？',
        examplePinyin: 'Běijīng tiānqì zěnmeyàng?',
        exampleVietnamese: 'Thời tiết Bắc Kinh thế nào?',
        radicals: '怎 + 么 + 样',
        mnemonic: 'Hỏi về tính chất hoặc tình trạng.'
      },
      {
        id: 'hsk1-12-03',
        hanzi: '太',
        pinyin: 'tài',
        vietnamese: 'quá / lắm',
        hanViet: 'Thái',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '太热了！',
        examplePinyin: 'Tài rè le!',
        exampleVietnamese: 'Nóng quá đi mất!',
        radicals: '大 (to lớn) + 丶 (dấu chấm)',
        mnemonic: 'Còn to lớn hơn cả 大 (đại) thì là 太 (quá mức).'
      },
      {
        id: 'hsk1-12-04',
        hanzi: '热',
        pinyin: 'rè',
        vietnamese: 'nóng',
        hanViet: 'Nhiệt',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '今天不热。',
        examplePinyin: 'Jīntiān bú rè.',
        exampleVietnamese: 'Hôm nay không nóng.',
        radicals: '执 + 灬 (hỏa/lửa)',
        mnemonic: 'Bốn chấm lửa (灬) bùng cháy tỏa ra nhiệt lượng nóng bỏng.'
      },
      {
        id: 'hsk1-12-05',
        hanzi: '冷',
        pinyin: 'lěng',
        vietnamese: 'lạnh / rét',
        hanViet: 'Lãnh',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '明天很冷。',
        examplePinyin: 'Míngtiān hěn lěng.',
        exampleVietnamese: 'Ngày mai rất lạnh.',
        radicals: '冫 (băng tuyết) + 令',
        mnemonic: 'Băng tuyết (冫) rơi buốt giá.'
      },
      {
        id: 'hsk1-12-06',
        hanzi: '下雨',
        pinyin: 'xià yǔ',
        vietnamese: 'mưa / đổ mưa',
        hanViet: 'Hạ vũ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '今天下雨了。',
        examplePinyin: 'Jīntiān xià yǔ le.',
        exampleVietnamese: 'Hôm nay trời đổ mưa rồi.',
        radicals: '下 (rơi xuống) + 雨 (mưa)',
        mnemonic: 'Những giọt nước mưa (雨) rơi xuống (下).'
      },
      {
        id: 'hsk1-12-07',
        hanzi: '小姐',
        pinyin: 'xiǎojiě',
        vietnamese: 'cô / tiểu thư / chị',
        hanViet: 'Tiểu tỷ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '王小姐，你好！',
        examplePinyin: 'Wáng xiǎojiě, nǐ hǎo!',
        exampleVietnamese: 'Chào cô Vương!',
        radicals: '小 (nhỏ) + 姐 (chị gái)',
        mnemonic: 'Cách xưng hô tôn kính với người phụ nữ trẻ.'
      },
      {
        id: 'hsk1-12-08',
        hanzi: '来',
        pinyin: 'lái',
        vietnamese: 'đến / tới',
        hanViet: 'Lai',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '他今天没来。',
        examplePinyin: 'Tā jīntiān méi lái.',
        exampleVietnamese: 'Hôm nay anh ấy không đến.',
        radicals: '木 + 丷',
        mnemonic: 'Hình ảnh bước chân tiến lại gần.'
      },
      {
        id: 'hsk1-12-09',
        hanzi: '身体',
        pinyin: 'shēntǐ',
        vietnamese: 'thân thể / sức khỏe',
        hanViet: 'Thân thể',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '你身体好吗？',
        examplePinyin: 'Nǐ shēntǐ hǎo ma?',
        exampleVietnamese: 'Sức khỏe của bạn tốt chứ?',
        radicals: '身 (thân mình) + 体 (thể xác)',
        mnemonic: 'Cơ thể và thể trạng của con người.'
      },
      {
        id: 'hsk1-12-10',
        hanzi: '爱',
        pinyin: 'ài',
        vietnamese: 'yêu / thích',
        hanViet: 'Ái',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '我不爱吃米饭。',
        examplePinyin: 'Wǒ bú ài chī mǐfàn.',
        exampleVietnamese: 'Tôi không thích ăn cơm.',
        radicals: '爫 + 冖 + 友 (bạn bè)',
        mnemonic: 'Bao bọc người thân yêu bằng tất cả tình cảm ấm áp.'
      },
      {
        id: 'hsk1-12-11',
        hanzi: '些',
        pinyin: 'xiē',
        vietnamese: 'một vài / những / chút',
        hanViet: 'Ta',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '买些水果。',
        examplePinyin: 'Mǎi xiē shuǐguǒ.',
        exampleVietnamese: 'Mua một vài loại hoa quả.',
        radicals: '止 + 匕 + 二',
        mnemonic: 'Chỉ số lượng một vài thứ.'
      },
      {
        id: 'hsk1-12-12',
        hanzi: '水果',
        pinyin: 'shuǐguǒ',
        vietnamese: 'hoa quả / trái cây',
        hanViet: 'Thủy quả',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '多吃水果。',
        examplePinyin: 'Duō chī shuǐguǒ.',
        exampleVietnamese: 'Ăn nhiều hoa quả.',
        radicals: '水 (nước) + 果 (quả)',
        mnemonic: 'Quả ngọt mọng nước (水).'
      },
      {
        id: 'hsk1-12-13',
        hanzi: '水',
        pinyin: 'shuǐ',
        vietnamese: 'nước',
        hanViet: 'Thủy',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 12: 明天天气怎么样',
        source: 'hsk1',
        exampleSentence: '多喝水。',
        examplePinyin: 'Duō hē shuǐ.',
        exampleVietnamese: 'Uống nhiều nước.',
        radicals: '水 (thủy)',
        mnemonic: 'Dòng nước chảy uốn lượn.'
      }
    ]
  },

  // =================== BÀI 13 ===================
  {
    lessonNumber: 13,
    title: 'Bài 13: Anh ấy đang học nấu món ăn Trung Quốc',
    hanziTitle: '他在学做中国菜呢 (Tā zài xué zuò Zhōngguó cài ne)',
    description: 'Từ vựng gọi điện thoại, hành động đang diễn ra và giải trí',
    words: [
      {
        id: 'hsk1-13-01',
        hanzi: '喂',
        pinyin: 'wèi',
        vietnamese: 'a-lô (khi nghe điện thoại)',
        hanViet: 'Uy',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 13: 他在学做中国菜呢',
        source: 'hsk1',
        exampleSentence: '喂，你在做什么？',
        examplePinyin: 'Wèi, nǐ zài zuò shénme?',
        exampleVietnamese: 'A-lô, bạn đang làm gì vậy?',
        radicals: '口 (khẩu/miệng) + 畏',
        mnemonic: 'Mở miệng (口) gọi a-lô khi bắt máy.'
      },
      {
        id: 'hsk1-13-02',
        hanzi: '在',
        pinyin: 'zài',
        vietnamese: 'đang (phó từ biểu thị hành động đang tiếp diễn)',
        hanViet: 'Tại',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 13: 他在学做中国菜呢',
        source: 'hsk1',
        exampleSentence: '我在看书。',
        examplePinyin: 'Wǒ zài kàn shū.',
        exampleVietnamese: 'Tôi đang đọc sách.',
        radicals: '𠂇 + 土',
        mnemonic: 'Biểu thị sự việc đang diễn ra.'
      },
      {
        id: 'hsk1-13-03',
        hanzi: '做',
        pinyin: 'zuò',
        vietnamese: 'làm / nấu',
        hanViet: 'Tác',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 13: 他在学做中国菜呢',
        source: 'hsk1',
        exampleSentence: '他在做饭。',
        examplePinyin: 'Tā zài zuò fàn.',
        exampleVietnamese: 'Anh ấy đang nấu cơm.',
        radicals: '亻 (nhân) + 故',
        mnemonic: 'Con người (亻) bắt tay làm việc.'
      },
      {
        id: 'hsk1-13-04',
        hanzi: '中国菜',
        pinyin: 'Zhōngguó cài',
        vietnamese: 'món ăn Trung Quốc',
        hanViet: 'Trung Quốc thái',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 13: 他在学做中国菜呢',
        source: 'hsk1',
        exampleSentence: '中国菜很好吃。',
        examplePinyin: 'Zhōngguó cài hěn hǎochī.',
        exampleVietnamese: 'Món ăn Trung Quốc rất ngon.',
        radicals: '中 + 国 + 菜 (thái/món rau)',
        mnemonic: 'Ẩm thực Trung Hoa đặc sắc.'
      },
      {
        id: 'hsk1-13-05',
        hanzi: '学',
        pinyin: 'xué',
        vietnamese: 'học / học tập',
        hanViet: 'Học',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 13: 他在学做中国菜呢',
        source: 'hsk1',
        exampleSentence: '我想学汉语。',
        examplePinyin: 'Wǒ xiǎng xué Hànyǔ.',
        exampleVietnamese: 'Tôi muốn học tiếng Trung.',
        radicals: '冖 + 子 (tử/trẻ nhỏ)',
        mnemonic: 'Đứa trẻ (子) ngồi học tập dưới mái trường che chở.'
      },
      {
        id: 'hsk1-13-06',
        hanzi: '睡觉',
        pinyin: 'shuì jiào',
        vietnamese: 'ngủ',
        hanViet: 'Thụy giác',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 13: 他在学做中国菜呢',
        source: 'hsk1',
        exampleSentence: '他在睡觉呢。',
        examplePinyin: 'Tā zài shuì jiào ne.',
        exampleVietnamese: 'Cậu ấy đang ngủ đấy.',
        radicals: '目 (mắt) + 垂 (rủ xuống)',
        mnemonic: 'Đôi mắt (目) rủ xuống (垂) chìm vào giấc ngủ.'
      },
      {
        id: 'hsk1-13-07',
        hanzi: '上午',
        pinyin: 'shàngwǔ',
        vietnamese: 'buổi sáng (khoảng 8h - 11h)',
        hanViet: 'Thượng ngọ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 13: 他在学做中国菜呢',
        source: 'hsk1',
        exampleSentence: '上午你做什么？',
        examplePinyin: 'Shàngwǔ nǐ zuò shénme?',
        exampleVietnamese: 'Buổi sáng bạn làm gì?',
        radicals: '上 (trước) + 午 (ngọ)',
        mnemonic: 'Thời gian trước buổi trưa.'
      },
      {
        id: 'hsk1-13-08',
        hanzi: '电视',
        pinyin: 'diànshì',
        vietnamese: 'ti-vi / truyền hình',
        hanViet: 'Điện thị',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 13: 他在学做中国菜呢',
        source: 'hsk1',
        exampleSentence: '他在看电视。',
        examplePinyin: 'Tā zài kàn diànshì.',
        exampleVietnamese: 'Anh ấy đang xem ti-vi.',
        radicals: '电 (điện) + 视 (thị/nhìn ngắm)',
        mnemonic: 'Nhìn ngắm (视) hình ảnh qua màn hình điện (电).'
      },
      {
        id: 'hsk1-13-09',
        hanzi: '喜欢',
        pinyin: 'xǐhuan',
        vietnamese: 'thích / ưa chuộng',
        hanViet: 'Hỷ hoan',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 13: 他在学做中国菜呢',
        source: 'hsk1',
        exampleSentence: '我喜欢喝茶。',
        examplePinyin: 'Wǒ xǐhuan hē chá.',
        exampleVietnamese: 'Tôi thích uống trà.',
        radicals: '喜 (hỷ/vui mừng) + 欠 (khiếm)',
        mnemonic: 'Niềm vui sướng xuất phát từ trái tim.'
      },
      {
        id: 'hsk1-13-10',
        hanzi: '给',
        pinyin: 'gěi',
        vietnamese: 'cho / tặng / đối với (hoặc gọi cho ai)',
        hanViet: 'Cấp',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 13: 他在学做中国菜呢',
        source: 'hsk1',
        exampleSentence: '我给他打电话。',
        examplePinyin: 'Wǒ gěi tā dǎ diànhuà.',
        exampleVietnamese: 'Tôi gọi điện thoại cho anh ấy.',
        radicals: '纟 (mịch/sợi tơ) + 合 (hợp)',
        mnemonic: 'Đem đồ gắn kết trao cho đối phương.'
      },
      {
        id: 'hsk1-13-11',
        hanzi: '打电话',
        pinyin: 'dǎ diànhuà',
        vietnamese: 'gọi điện thoại',
        hanViet: 'Đả điện thoại',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 13: 他在学做中国菜呢',
        source: 'hsk1',
        exampleSentence: '他在打电话。',
        examplePinyin: 'Tā zài dǎ diànhuà.',
        exampleVietnamese: 'Anh ấy đang gọi điện thoại.',
        radicals: '打 (bấm/đánh) + 电话 (điện thoại)',
        mnemonic: 'Bấm số truyền lời nói qua sóng điện.'
      },
      {
        id: 'hsk1-13-12',
        hanzi: '吧',
        pinyin: 'ba',
        vietnamese: 'nhé / đi / nha (trợ từ ngữ khí gợi ý/khuyên nhủ)',
        hanViet: 'Ba',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 13: 他在学做中国菜呢',
        source: 'hsk1',
        exampleSentence: '我们去喝咖啡吧！',
        examplePinyin: 'Wǒmen qù hē kāfēi ba!',
        exampleVietnamese: 'Chúng mình đi uống cà phê đi!',
        radicals: '口 (miệng) + 巴',
        mnemonic: 'Lời nói nhẹ nhàng đưa ra lời rủ rê.'
      }
    ]
  },

  // =================== BÀI 14 ===================
  {
    lessonNumber: 14,
    title: 'Bài 14: Cô ấy đã mua không ít quần áo',
    hanziTitle: '她买了不少衣服 (Tā mǎi le bùshǎo yīfu)',
    description: 'Từ vựng mua sắm, đồ đạc, khen ngợi trang phục đẹp và thời gian',
    words: [
      {
        id: 'hsk1-14-01',
        hanzi: '东西',
        pinyin: 'dōngxi',
        vietnamese: 'đồ đạc / đồ vật / thứ',
        hanViet: 'Đông tây',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '你买什么东西？',
        examplePinyin: 'Nǐ mǎi shénme dōngxi?',
        exampleVietnamese: 'Bạn mua đồ gì thế?',
        radicals: '东 (đông) + 西 (tây)',
        mnemonic: 'Đồ đạc gom từ bốn phương Đông Tây.'
      },
      {
        id: 'hsk1-14-02',
        hanzi: '一点儿',
        pinyin: 'yìdiǎnr',
        vietnamese: 'một chút / một ít',
        hanViet: 'Nhất điểm nhi',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '我买了一点儿苹果。',
        examplePinyin: 'Wǒ mǎi le yìdiǎnr píngguǒ.',
        exampleVietnamese: 'Tôi đã mua một ít táo.',
        radicals: '一 + 点 + 儿',
        mnemonic: 'Số lượng nhỏ bé.'
      },
      {
        id: 'hsk1-14-03',
        hanzi: '苹果',
        pinyin: 'píngguǒ',
        vietnamese: 'quả táo',
        hanViet: 'Bình quả',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '苹果很好吃。',
        examplePinyin: 'Píngguǒ hěn hǎochī.',
        exampleVietnamese: 'Táo rất ngon.',
        radicals: '艹 (cỏ) + 平 (bình an) + 果 (quả)',
        mnemonic: 'Quả ăn vào mang lại sự bình an tốt lành.'
      },
      {
        id: 'hsk1-14-04',
        hanzi: '看见',
        pinyin: 'kànjiàn',
        vietnamese: 'nhìn thấy / trông thấy',
        hanViet: 'Khán kiến',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '你看见他了吗？',
        examplePinyin: 'Nǐ kànjiàn tā le ma?',
        exampleVietnamese: 'Bạn có nhìn thấy anh ấy không?',
        radicals: '看 (nhìn) + 见 (thấy)',
        mnemonic: 'Đưa mắt nhìn (看) và nhận ra hình bóng (见).'
      },
      {
        id: 'hsk1-14-05',
        hanzi: '先生',
        pinyin: 'xiānsheng',
        vietnamese: 'ngài / ông / chồng / thầy (tiên sinh)',
        hanViet: 'Tiên sinh',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '张先生来了。',
        examplePinyin: 'Zhāng xiānsheng lái le.',
        exampleVietnamese: 'Ông Trương đến rồi.',
        radicals: '先 (trước) + 生 (sinh ra)',
        mnemonic: 'Người sinh ra trước để chỉ sự tôn kính.'
      },
      {
        id: 'hsk1-14-06',
        hanzi: '开',
        pinyin: 'kāi',
        vietnamese: 'lái (xe) / mở (cửa)',
        hanViet: 'Khai',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '他会开车。',
        examplePinyin: 'Tā huì kāi chē.',
        exampleVietnamese: 'Anh ấy biết lái xe.',
        radicals: '一 + 廾 (hai cánh tay)',
        mnemonic: 'Hai bàn tay mở rộng cánh cửa đón chào.'
      },
      {
        id: 'hsk1-14-07',
        hanzi: '车',
        pinyin: 'chē',
        vietnamese: 'xe / xe cộ',
        hanViet: 'Xa',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '这是他的车。',
        examplePinyin: 'Zhè shì tā de chē.',
        exampleVietnamese: 'Đây là xe của anh ấy.',
        radicals: '车 (xa/xe cộ)',
        mnemonic: 'Hình ảnh chiếc xe có trục và 2 bánh lăn.'
      },
      {
        id: 'hsk1-14-08',
        hanzi: '回来',
        pinyin: 'huílái',
        vietnamese: 'trở về / về lại đây',
        hanViet: 'Hồi lai',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '他什么时候回来？',
        examplePinyin: 'Tā shénme shíhou huílái?',
        exampleVietnamese: 'Khi nào anh ấy quay về?',
        radicals: '回 (về) + 来 (đến)',
        mnemonic: 'Quay trở lại nơi này.'
      },
      {
        id: 'hsk1-14-09',
        hanzi: '分钟',
        pinyin: 'fēnzhōng',
        vietnamese: 'phút (đo lường khoảng thời gian)',
        hanViet: 'Phân chung',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '四十分钟后。',
        examplePinyin: 'Sìshí fēnzhōng hòu.',
        exampleVietnamese: '40 phút sau.',
        radicals: '分 (phút) + 钟 (chuông/đồng hồ)',
        mnemonic: 'Đo lường từng phút trên mặt đồng hồ.'
      },
      {
        id: 'hsk1-14-10',
        hanzi: '后',
        pinyin: 'hòu',
        vietnamese: 'sau / sau khi',
        hanViet: 'Hậu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '三天后。',
        examplePinyin: 'Sān tiān hòu.',
        exampleVietnamese: '3 ngày sau.',
        radicals: '后 (hậu/sau)',
        mnemonic: 'Thời điểm xảy ra về sau.'
      },
      {
        id: 'hsk1-14-11',
        hanzi: '衣服',
        pinyin: 'yīfu',
        vietnamese: 'quần áo / y phục',
        hanViet: 'Y phục',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '这件衣服很漂亮。',
        examplePinyin: 'Zhè jiàn yīfu hěn piàoliang.',
        exampleVietnamese: 'Bộ quần áo này rất đẹp.',
        radicals: '衣 (y/áo) + 服 (phục)',
        mnemonic: 'Trang phục mặc trên người.'
      },
      {
        id: 'hsk1-14-12',
        hanzi: '漂亮',
        pinyin: 'piàoliang',
        vietnamese: 'đẹp / xinh đẹp / tuyệt vời',
        hanViet: 'Phiêu lượng',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '她很漂亮。',
        examplePinyin: 'Tā hěn piàoliang.',
        exampleVietnamese: 'Cô ấy rất xinh đẹp.',
        radicals: '氵 (nước) + 票 + 亮 (sáng sủa)',
        mnemonic: 'Vẻ đẹp trong trẻo lấp lánh như làn nước (氵) sáng ngời (亮).'
      },
      {
        id: 'hsk1-14-13',
        hanzi: '啊',
        pinyin: 'a',
        vietnamese: 'à / nha / nhỉ (trợ từ cảm thán)',
        hanViet: 'A',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '太好了啊！',
        examplePinyin: 'Tài hǎo le a!',
        exampleVietnamese: 'Tuyệt quá đi nha!',
        radicals: '口 (miệng) + 阿',
        mnemonic: 'Mở miệng thốt lên lời khen ngợi.'
      },
      {
        id: 'hsk1-14-14',
        hanzi: '少',
        pinyin: 'shǎo',
        vietnamese: 'ít',
        hanViet: 'Thiểu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '这里的书很少。',
        examplePinyin: 'Zhèlǐ de shū hěn shǎo.',
        exampleVietnamese: 'Sách ở đây rất ít.',
        radicals: '小 (nhỏ) + 丿',
        mnemonic: 'Số lượng ít ỏi.'
      },
      {
        id: 'hsk1-14-15',
        hanzi: '不少',
        pinyin: 'bùshǎo',
        vietnamese: 'không ít / nhiều',
        hanViet: 'Bất thiểu',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '她买了不少衣服。',
        examplePinyin: 'Tā mǎi le bùshǎo yīfu.',
        exampleVietnamese: 'Cô ấy đã mua không ít quần áo.',
        radicals: '不 (không) + 少 (ít)',
        mnemonic: 'Không ít tức là rất nhiều.'
      },
      {
        id: 'hsk1-14-16',
        hanzi: '这些',
        pinyin: 'zhèxiē',
        vietnamese: 'những thứ này / những cái này',
        hanViet: 'Giá ta',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '这些都是苹果。',
        examplePinyin: 'Zhèxiē dōu shì píngguǒ.',
        exampleVietnamese: 'Những cái này đều là quả táo.',
        radicals: '这 (này) + 些 (những)',
        mnemonic: 'Chỉ nhóm sự vật ở gần.'
      },
      {
        id: 'hsk1-14-17',
        hanzi: '都',
        pinyin: 'dōu',
        vietnamese: 'đều / tất cả',
        hanViet: 'Đô',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 14: 她买了不少衣服',
        source: 'hsk1',
        exampleSentence: '我们都是学生。',
        examplePinyin: 'Wǒmen dōu shì xuésheng.',
        exampleVietnamese: 'Chúng tôi đều là học sinh.',
        radicals: '者 + 阝 (ấp)',
        mnemonic: 'Tất cả mọi người trong thành đô đều như vậy.'
      }
    ]
  },

  // =================== BÀI 15 ===================
  {
    lessonNumber: 15,
    title: 'Bài 15: Tôi đến đây bằng máy bay',
    hanziTitle: '我是坐飞机来的 (Wǒ shì zuò fēijī lái de)',
    description: 'Từ vựng về phương tiện giao thông, máy bay, taxi, năm tháng và làm quen',
    words: [
      {
        id: 'hsk1-15-01',
        hanzi: '认识',
        pinyin: 'rènshi',
        vietnamese: 'quen biết / nhận biết',
        hanViet: 'Nhận thức',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 15: 我是坐飞机来的',
        source: 'hsk1',
        exampleSentence: '认识你很高兴！',
        examplePinyin: 'Rènshi nǐ hěn gāoxìng!',
        exampleVietnamese: 'Rất vui được quen biết bạn!',
        radicals: '讠 (ngôn) + 认 + 识',
        mnemonic: 'Dùng lời nói (讠) giao tiếp để nhận biết và quen nhau.'
      },
      {
        id: 'hsk1-15-02',
        hanzi: '年',
        pinyin: 'nián',
        vietnamese: 'năm',
        hanViet: 'Niên',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 15: 我是坐飞机来的',
        source: 'hsk1',
        exampleSentence: '我们2011年认识的。',
        examplePinyin: 'Wǒmen èr líng yī yī nián rènshi de.',
        exampleVietnamese: 'Chúng tôi quen nhau vào năm 2011.',
        radicals: '干 + 人',
        mnemonic: 'Vụ mùa thu hoạch mỗi năm.'
      },
      {
        id: 'hsk1-15-03',
        hanzi: '大学',
        pinyin: 'dàxué',
        vietnamese: 'trường đại học',
        hanViet: 'Đại học',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 15: 我是坐飞机来的',
        source: 'hsk1',
        exampleSentence: '我们在大学认识的。',
        examplePinyin: 'Wǒmen zài dàxué rènshi de.',
        exampleVietnamese: 'Chúng tôi quen nhau ở trường đại học.',
        radicals: '大 (to lớn) + 学 (học)',
        mnemonic: 'Bậc học lớn cao nhất.'
      },
      {
        id: 'hsk1-15-04',
        hanzi: '饭店',
        pinyin: 'fàndiàn',
        vietnamese: 'nhà hàng / khách sạn / tiệm ăn',
        hanViet: 'Phạn điếm',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 15: 我是坐飞机来的',
        source: 'hsk1',
        exampleSentence: '他在饭店工作。',
        examplePinyin: 'Tā zài fàndiàn gōngzuò.',
        exampleVietnamese: 'Anh ấy làm việc ở khách sạn/nhà hàng.',
        radicals: '饭 (cơm) + 店 (tiệm/quán)',
        mnemonic: 'Cửa tiệm (店) phục vụ ăn uống (饭).'
      },
      {
        id: 'hsk1-15-05',
        hanzi: '出租车',
        pinyin: 'chūzūchē',
        vietnamese: 'xe tắc-xi',
        hanViet: 'Xuất tô xa',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 15: 我是坐飞机来的',
        source: 'hsk1',
        exampleSentence: '我们坐出租车去。',
        examplePinyin: 'Wǒmen zuò chūzūchē qù.',
        exampleVietnamese: 'Chúng tôi đi bằng xe taxi.',
        radicals: '出 (ra) + 租 (thuê) + 车 (xe)',
        mnemonic: 'Chiếc xe (车) cho thuê (租) chở khách ra ngoài (出).'
      },
      {
        id: 'hsk1-15-06',
        hanzi: '一起',
        pinyin: 'yìqǐ',
        vietnamese: 'cùng nhau / cùng một chỗ',
        hanViet: 'Nhất khởi',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 15: 我是坐飞机来的',
        source: 'hsk1',
        exampleSentence: '我们一起去吃饭吧。',
        examplePinyin: 'Wǒmen yìqǐ qù chī fàn ba.',
        exampleVietnamese: 'Chúng mình cùng nhau đi ăn cơm nhé.',
        radicals: '一 (nhất) + 起 (khởi)',
        mnemonic: 'Cùng nhau khởi đầu hành trình.'
      },
      {
        id: 'hsk1-15-07',
        hanzi: '高兴',
        pinyin: 'gāoxìng',
        vietnamese: 'vui vẻ / hân hạnh / phấn khởi',
        hanViet: 'Cao hứng',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 15: 我是坐飞机来的',
        source: 'hsk1',
        exampleSentence: '今天我很高兴。',
        examplePinyin: 'Jīntiān wǒ hěn gāoxìng.',
        exampleVietnamese: 'Hôm nay tôi rất vui.',
        radicals: '高 (cao) + 兴 (hứng)',
        mnemonic: 'Tâm trạng phấn chấn cao hứng.'
      },
      {
        id: 'hsk1-15-08',
        hanzi: '听',
        pinyin: 'tīng',
        vietnamese: 'nghe',
        hanViet: 'Thính',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 15: 我是坐飞机来的',
        source: 'hsk1',
        exampleSentence: '你听，这是什么声音？',
        examplePinyin: 'Nǐ tīng, zhè shì shénme shēngyīn?',
        exampleVietnamese: 'Bạn nghe xem, đây là âm thanh gì vậy?',
        radicals: '口 (miệng) + 斤',
        mnemonic: 'Lắng nghe âm thanh từ miệng phát ra.'
      },
      {
        id: 'hsk1-15-09',
        hanzi: '飞机',
        pinyin: 'fēijī',
        vietnamese: 'máy bay / phi cơ',
        hanViet: 'Phi cơ',
        hskLevel: 1,
        lesson: 'HSK 1 - Bài 15: 我是坐飞机来的',
        source: 'hsk1',
        exampleSentence: '他是坐飞机来的。',
        examplePinyin: 'Tā shì zuò fēijī lái de.',
        exampleVietnamese: 'Anh ấy đến đây bằng máy bay.',
        radicals: '飞 (bay) + 机 (cỗ máy)',
        mnemonic: 'Cỗ máy (机) có thể bay lượn (飞) trên bầu trời.'
      }
    ]
  }
];


export const HSK1_LESSON_WORDS = HSK1_ALL_LESSONS.flatMap(lesson => lesson.words.map(w => ({ ...w, box: 1, isStarred: false, reviewCount: 0, correctCount: 0, wrongCount: 0, createdAt: Date.now() })));
